let paragraphss = {
    "Stardust": {
        "Frank L Curwen": "we are all made of stardust because when one star dies another million are born and in that one moment of pure energy all that is perfect in you and me and all that is alive all around us comes into being for what may seem like an eternity but on the whole grand scale of things is just a flicker of a light the vast darkness out there the emptiness we call space will one day envelope not only you and me but even those magic stars and all their stardust and in that final moment everything will have come full circle and we shall once again look forward to our rebirth ",
        "Frank Curwen": "We are all made of stardust, because when one star dies, another million are born, and in that one moment of pure energy, all that is perfect in you and me and all that is alive all around us, comes into being for what may seem like an eternity but on the whole grand scale of things is just a flicker of a light. The vast darkness out there, the emptiness we call space, will one day envelope not only you and me but even those magic stars and all their stardust, and in that final moment, everything will have come full circle and we shall once again look forward to our rebirth. "
    },
    "Love": {
        "Frank L Curwen": "life is the most wonderful thing that has ever happened to you me and anyone else around the world who has ever taken the time to open their eyes and really look around at all the amazing things right on their own doorstep and even if you have never thought about how beautiful life can actually be because you have been stuck behind a screen for most of your time on this wonderful blue and green marvel then it is time for you me and anoyone else willing to to do something about it and give mother earth what she has craved all along that beautiful big fullfat love ",
        "Frank Curwen": "Life is the most wonderful thing that has ever happened to you, me and anyone else around the world who has ever taken the time to open their eyes and really look around at all the amazing things right on their own doorstep. And even if you have never thought about how beautiful life can actually be because you have been stuck behind a screen for most of your time on this wonderful blue and green marvel, then it is time for you, me and anoyone else willing to, to do something about it and give mother earth what she has craved all along, that beautiful big full-fat love. "
    },
    "Everlasting": {
        "Frank L Curwen": "love is wonderful love is that dream that we all hope never to wake from that we all hope never finishes it is that dream that we all try desperately to reenter once we have awoken from it love makes us feel like we were floating through the world in a bubble shared only by that which we love our love does not have to be sexual it does not even have to be animate it just needs to be there because love is that which saves us from the world this cold heartless world where would we all be without our undying unfaltering love that is why our quest for that everlasting love must continue ",
        "Frank Curwen": "Love is wonderful. Love is that dream that we all hope never to wake from, that we all hope never finishes. It is that dream that we all try desperately to reenter once we have awoken from it. Love makes us feel like we were floating through the world in a bubble, shared only by that which we love. Our love does not have to be sexual, it does not even have to be animate, it just needs to be there because love is that which saves us from the world, this cold, heartless world. Where would we all be without our undying, unfaltering love. That is why our quest for that everlasting love must continue. "
    },
    "Njuta": {
        "Frank L Curwen": "livet ska njutas av det finns det ingen tvekan om men om vi faktiskt njuter av våra liv det finns det mycket tvivlan om att kunna njuta av livet måste man först och främst kunna se livet med sina egna ögon vilket betyder att man måste släppa telefonen man kan inte se livet genom en inspelningsruta på telefonskärmen då kan man lika gärna sitta framför datorn och kolla på någan annan som också njuter av livet på samma sätt livet är magiskt och det finns bara ett sätt att se det magiska med egna ögon och utan distraktoner så släpp mobilen och njut tillfullo ",
        "Frank Curwen": "Livet ska njutas av, det finns det ingen tvekan om, men om vi faktiskt njuter av våra liv, det finns det mycket tvivlan om. Att kunna njuta av livet måste man först och främst kunna se livet med sina egna ögon, vilket betyder att man måste släppa telefonen. Man kan inte se livet genom en inspelningsruta på telefonskärmen, då kan man lika gärna sitta framför datorn och kolla på någan annan som också \"njuter av livet\" på samma sätt. Livet är magiskt och det finns bara ett sätt att se det magiska, med egna ögon och utan distraktoner, så släpp mobilen och njut tillfullo. "
    },
    "Ändring": {
        "Frank L Curwen": "om man någongång haft en dröm om att ändra någonting kanske i ditt liv eller kanske lite större så som på jobbet eller ändra någonting i hela världen om man har haft någon av dessa drömmar vad är det du väntar på det är bara göra livet kommer bara en gång och då ska man ta alla möjligheter som finns och om det är någonting som man inte håller med om då ska man ändra det livet behöver det livet till och med kräver det för livet vill inte stagnera och bara dö den vill utvecklas och leva tills det inte går att leva mer och det betyder att man ska ändra det som blockerar livet att kunna leva ",
        "Frank Curwen": "Om man någongång haft en dröm om att ändra någonting, kanske i ditt liv eller kanske lite större, så som på jobbet eller ändra någonting i hela världen. Om man har haft någon av dessa drömmar, vad är det du väntar på? Det är bara göra. Livet kommer bara en gång och då ska man ta alla möjligheter som finns och om det är någonting som man inte håller med om, då ska man ändra det. Livet behöver det, livet till och med kräver det för livet vill inte stagnera och bara dö, den vill utvecklas och leva tills det inte går att leva mer, och det betyder att man ska ändra det som blockerar livet att kunna leva. "
    },
    "Världen": {
        "Frank L Curwen": "man slutar aldrig lära sig saker för det finns så mycket i världen man kan lära sig från detta är för att världen är så fantastiskt bra världen vill att du lär dig saker och det är därför du blir testad konstant världen vill testa dig för att den vill att du blir bättre den vill ge dig chansen att förbättra dig för att den vill att du ska vara kvar här så länge som möjligt våra liv våran glädje världen frodas på detta och fortsätter att ge oss mer och mer utmaningar bara för att hjälpa oss leva våra bästa möjliga liv ett stort tack till vår härliga värld ",
        "Frank Curwen": "Man slutar aldrig lära sig saker för det finns så mycket i världen man kan lära sig från. Detta är för att världen är så fantastiskt bra. Världen vill att du lär dig saker och det är därför du blir \"testad\" konstant. Världen vill testa dig för att den vill att du blir bättre. Den vill ge dig chansen att förbättra dig för att den vill att du ska vara kvar här så länge som möjligt. Våra liv, våran glädje, världen frodas på detta och fortsätter att ge oss mer och mer utmaningar bara för att hjälpa oss leva våra bästa möjliga liv. Ett stort tack till vår härliga värld. "
    }
};